TUP Rating Slip mini project
- Rating slip is a simply a pdf document where students can see their grades for a certain semester.

In [1]:
# importing the required libraries
import pandas as pd
import numpy as np

In [6]:
# creaating a table for grades
grades = {
    'Subjects': [ 'Understanding the Self', 
    'Readings in Philippine History',
    'Life and Works of Rizal',
    'Signals, Spectra, and Signal Processing (Lec)' ,
    'Signals, Spectra, and Signal Processing (Lab)',
    'Communications 2: Modulation and Coding Techniques (Lec)',
    'Communications 2: Modulation and Coding Techniques (Lab)',
    'Electronics 3: Electronic Systems and Design (Lec)',
    'Electronics 3: Electronic Systems and Design (Lab)',
    'Digital Electronics 1: Logic Circuits and Switching Theory (Lec)',
    'Digital Electronics 1: Logic Circuits and Switching Theory (Lab)',        
    ],
    
    # input of your own grades
    # my grades cutie
    'Grades': [1.00, 1.50, 1.00, 2.75, 2.75, 1.75, 1.25, 2.00, 2.00, 2.25, 2.00], 
    'Credit': [3, 3, 3, 3, 1, 3,1, 3, 1, 3, 1]
}



grades_df = pd.DataFrame(grades)
print(grades_df)

                                             Subjects  Grades  Credit
0                              Understanding the Self    1.00       3
1                      Readings in Philippine History    1.50       3
2                             Life and Works of Rizal    1.00       3
3       Signals, Spectra, and Signal Processing (Lec)    2.75       3
4       Signals, Spectra, and Signal Processing (Lab)    2.75       1
5   Communications 2: Modulation and Coding Techni...    1.75       3
6   Communications 2: Modulation and Coding Techni...    1.25       1
7   Electronics 3: Electronic Systems and Design (...    2.00       3
8   Electronics 3: Electronic Systems and Design (...    2.00       1
9   Digital Electronics 1: Logic Circuits and Swit...    2.25       3
10  Digital Electronics 1: Logic Circuits and Swit...    2.00       1

In [7]:
# changing the index label
grades_df.index = ['GEC1-M', 'GEC2-M', 'GEM14-M', 'PECEC1B-M', 'PECEC1BL-M', 'PECEC2-M', 'PECEC2L-M', 'PECEE3-M', 'PECEE3L-M', 'PECEE4-M', 'PECEE4L-M']
grades_df

                                                     Subjects  Grades  Credit
GEC1-M                                 Understanding the Self    1.00       3
GEC2-M                         Readings in Philippine History    1.50       3
GEM14-M                               Life and Works of Rizal    1.00       3
PECEC1B-M       Signals, Spectra, and Signal Processing (Lec)    2.75       3
PECEC1BL-M      Signals, Spectra, and Signal Processing (Lab)    2.75       1
PECEC2-M    Communications 2: Modulation and Coding Techni...    1.75       3
PECEC2L-M   Communications 2: Modulation and Coding Techni...    1.25       1
PECEE3-M    Electronics 3: Electronic Systems and Design (...    2.00       3
PECEE3L-M   Electronics 3: Electronic Systems and Design (...    2.00       1
PECEE4-M    Digital Electronics 1: Logic Circuits and Swit...    2.25       3
PECEE4L-M   Digital Electronics 1: Logic Circuits and Swit...    2.00       1

In [8]:
# computation of grades
product = grades_df['Grades'] * grades_df['Credit']
gwa = sum(product) / sum(grades_df['Credit'])

print('GWA: ' + str(gwa))

GWA: 1.79

In [9]:
# Adding a new column for grades status
grades_status = []

for column in grades_df['Grades']:
    if column <= float(3) or column >= float(1):
        grades_status.append('PASSED')
    else:
        grades_status.append('FAILED')


grades_df['Grade Status'] = grades_status

# Some Details
print('Name: Kevin Carl B. Ricafort')
print('Course: Bachelor of Science in Elctronics Engineering')
print('GWA: '+ str(gwa))

grades_df

Name: Kevin Carl B. Ricafort
Course: Bachelor of Science in Elctronics Engineering
GWA: 1.79

,Subjects,Grades,Credit,Grade Status
GEC1-M,Understanding the Self,1.00,3,PASSED
GEC2-M,Readings in Philippine History,1.50,3,PASSED
GEM14-M,Life and Works of Rizal,1.00,3,PASSED
PECEC1B-M,"Signals, Spectra, and Signal Processing (Lec)",2.75,3,PASSED
PECEC1BL-M,"Signals, Spectra, and Signal Processing (Lab)",2.75,1,PASSED
PECEC2-M,Communications 2: Modulation and Coding Techni...,1.75,3,PASSED
PECEC2L-M,Communications 2: Modulation and Coding Techni...,1.25,1,PASSED
PECEE3-M,Electronics 3: Electronic Systems and Design (...,2.00,3,PASSED
PECEE3L-M,Electronics 3: Electronic Systems and Design (...,2.00,1,PASSED
PECEE4-M,Digital Electronics 1: Logic Circuits and Swit...,2.25,3,PASSED
PECEE4L-M,Digital Electronics 1: Logic Circuits and Swit...,2.00,1,PASSED